openapi: 3.0.0
info:
  title: Multi Step Form
  description: API
  version: 0.1.9

servers:
  - url: https://parking-app-api-production.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
