openapi: 3.0.0
info:
  title: Multi Step Form
  description: API
  version: 0.1.9

servers:
  - url: https://parking-app-api-production.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /form:
    post:
      summary: Create a new form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phoneNumber:
                  type: string
                plan:
                  type: string
                billing:
                  type: string
                addons:
                  type: string
                  items:
                    type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  phoneNumber:
                    type: string
                  plan:
                    type: string
                  billing:
                    type: string
                  addons:
                    type: array
                    items:
                      type: string
